renetflix/pelisyseries/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import *
from . import views
from .forms import UserPasswordResetForm, UserSetPasswordForm, CambiarPasswordForm

app_name = 'pelisyseries'
urlpatterns = [ 
    path('', views.home, name='home' ),
    path('index', views.index, name='index' ),
    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login' ),
    path('logout/', views.logout_request, name='logout' ),
    path('peliculas/', views.peliculas, name='peliculas'),
    path('series/', views.series, name='series'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/accion/', views.accion, name='accion'),
    path('categorias/animacion/', views.animacion, name='animacion'),
    path('categorias/aventura/', views.aventura, name='aventura'),
    path('categorias/terror/', views.terror, name='terror'),
    path('categorias/ciencia_ficcion/', views.ciencia_ficcion, name='ciencia_ficcion'),
    path('categorias/comedia/', views.comedia, name='comedia'),
    path('categorias/drama/', views.drama, name='drama'),
    path('categorias/familiar/', views.familiar, name='familiar'),
    path('categorias/fantasia/', views.fantasia, name='fantasia'),
    path('categorias/misterio/', views.misterio, name='misterio'),
    path('categorias/musicales/', views.musicales, name='musicales'),
    path('recientes/', views.recientes, name='recientes'),
    path('perfil/', views.perfil, name='perfil'),
    path('editar-perfil/', views.EditarPerfil.as_view(), name='editar-perfil'), 
    path('reproducir/<int:id>', views.Reproduccion, name='reproducir'), 
    path('me_gusta/<int:id>', views.Me_gusta, name='me_gusta'),  
    path('favoritos/<int:id>', views.Favoritos, name='favoritos'),  
    path('favoritos/', views.Favoritos_lista, name='favoritos_lista'),  
    path('busqueda/', views.Busqueda, name='busqueda'),  

    path('change_password/', PasswordChangeView.as_view(template_name='registration/change_password.html', form_class=CambiarPasswordForm, success_url = '/'), name='change_password'),

    path('password_reset/', PasswordResetView.as_view(form_class=UserPasswordResetForm, success_url = reverse_lazy('pelisyseries:password_reset_done')), name='password_reset'),  
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),  
    path('password_reset_confirm/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(form_class=UserSetPasswordForm, success_url = reverse_lazy('pelisyseries:password_reset_complete')), name='password_reset_confirm'),  
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),  
]

renetflix/renetflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pelisyseries.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

renetflix/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"> -->
    <script src="https://kit.fontawesome.com/1986a781d6.js" crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body class="bg-dark">
    {% if user.is_authenticated %}
    <nav class="px-5 navbar navbar-expand-lg bg-danger bg-gradient">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'pelisyseries:index' %}"><strong><h3 class="fw-bolder fs-2">Renetflix</h3></strong></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="mx-3 nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pelisyseries:peliculas' %}"><h6 class="text-white">Peliculas</h6></a>
                    </li>
                    <li class="mx-3 nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pelisyseries:series' %}"><h6 class="text-white">Series</h6></a>
                    </li>
                    <li class="mx-3 nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pelisyseries:categorias' %}"><h6 class="text-white">Categorías</h6></a>
                    </li>
                    <li class="mx-3 nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'pelisyseries:recientes' %}"><h6 class="text-white">Agregadas recientemente</h6></a>
                    </li> 
                </ul>
                <form class="me-5 d-flex" role="search" method="POST" action="{% url 'pelisyseries:busqueda' %}" autocomplete="off">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search" name="buscar">
                    <button class="btn btn-dark" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>
            </div>
            <div class="ms-2 dropdown-center">
                <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-user"></i> {{user.username}}
                </button>
                <ul class="dropdown-menu dropdown-menu-dark">
                  <li><a class="dropdown-item" href="{% url 'pelisyseries:perfil' %}"><i class="fa-solid fa-gear"></i> Cuenta</a></li>
                  <li><a class="dropdown-item" href="{% url 'pelisyseries:favoritos_lista' %}"><i class="fa-solid fa-heart"></i> Favoritos</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'pelisyseries:logout' %}"><i class="fa-solid fa-right-from-bracket"></i> Cerrar sesión</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% else %}
        <nav class="px-5 navbar navbar-expand-lg bg-danger bg-gradient">
            <div class="container-fluid">
                <strong><h3 class="fw-bolder fs-2">Renetflix</h3></strong>
            </div>
        </nav>
    {% endif %}
    
    {% if messages %}
        {% for message in messages %}
        <div class="mt-3 mx-auto w-25 alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}

    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>