ecomerce/ecomerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecomerce/store/urls.py
from django.urls import path 
from . import views

app_name = 'store'
urlpatterns = [ 
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
]

ecomerce/store/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    # se usa OneToOneField porque un usuario solo puede tener un cliente y visceversa
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

ecomerce/store/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
from .models import *

def store(request):
    product = Product.objects.all()
    context = {'product':product}
    return render(request, 'store/store.html', context)

def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
    context = {'items':items, 'order': order}
    return render(request, 'store/cart.html', context)

def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
    else:
        order = {'get_cart_total':0, 'get_cart_items':0}
        items = []
    context = {'items': items, 'order':order}
    return render(request, 'store/checkout.html', context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

ecomerce/store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a href="{% url 'store:store' %}" class="btn btn-outline-dark">&#x2190; Continue Shopping</a>
                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total: <strong>${{order.get_cart_total}}</strong></h5></th>
                        <th>
                            <a style="float:right; margin:5px;" href="{% url 'store:checkout' %}" class="btn btn-success">Checkout</a>
                        </th>
                    </tr>
                </table>
            </div>
            <br>
            <div class="box-element">
                {% for i in items %}
                <div class="cart-row">
                    <div style="flex:2"><img src="{{i.product.imageURL}}" alt="" class="row-image"></div>
                    <div style="flex:2"><p>{{i.product.name}}</p></div>
                    <div style="flex:1"><p>{{i.product.price|floatformat:2}}</p></div>
                    <div style="flex:1">
                        <p class="quantity">x{{i.quantity}}</p>
                        <div class="quantity">
                            <img src="{% static 'images/arrowup.png' %}" alt="" class="chg-quantity">
                            <img src="{% static 'images/arrowdown.png' %}" alt="" class="chg-quantity">
                        </div>
                    </div>
                    <div style="flex:1"><p>{{i.get_total}}</p></div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    
{% endblock %}

ecomerce/store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <dvi class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    <dvi id="user-info">
                        <div class="form-field">
                            <input required type="text" class="form-control" name="name" placeholder="Name...">
                        </div>
                        <div class="form-field">
                            <input required type="email" class="form-control" name="email" placeholder="Email...">
                        </div>
                    </dvi>
                    <div id="shipping-info">
                        <hr>
                        <p>Shipping Information</p>
                        <div class="form-field">
                            <input type="text" class="form-control" name="address" placeholder="Address...">
                        </div>
                        <div class="form-field">
                            <input type="text" class="form-control" name="city" placeholder="City...">
                        </div>
                        <div class="form-field">
                            <input type="text" class="form-control" name="state" placeholder="State...">
                        </div>
                        <div class="form-field">
                            <input type="text" class="form-control" name="zipcode" placeholder="Zip Code...">
                        </div>
                        <div class="form-field">
                            <input type="text" class="form-control" name="country" placeholder="Country...">
                        </div>
                    </div>
                    <hr>
                    <input type="submit" id="form-buttom" class="btn btn-success btn-block" value="Continue">
                </form>
            </div>
            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="box-element">
                <a href="{% url 'store:cart' %}" class="btn btn-outline-dark">&#x2190; Back to cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img src="{{item.product.imageURL}}" alt="" class="row-image"></div>
                        <div style="flex:2"><p>{{item.product.name}}</p></div>
                        <div style="flex:1"><p>{{item.product.price|floatformat:2}}</p></div>
                        <div style="flex:1"><p>{{item.quantity}}</p></div>
                    </div>
                {% endfor %}
                <h5>Items: {{order.get_cart_items}}</h5>
                <h5>Total: ${{order.get_cart_total|floatformat:2}}</h5>
            </div>
        </div>
    </dvi>
    
{% endblock %}

ecomerce/store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script type="text/javascript">
        var user = '{{request.user}}'
        function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i<cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1)===(name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getToken('csrftoken');
    </script>
    <title>E-commerce</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'store:store' %}">E-commerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <div class="form-inline my-2 my-lg-0">
                <a href="#"class="btn btn-warning">Login</a>            
                <a href="{% url 'store:cart' %}">
                   <img  id="cart-icon" src="{% static 'images/cart.png' %}">
               </a>
               <p id="cart-total">0</p>
           </div>
        </div>
    </nav>
    <hr>

    <div class="container">
        <br>
        {% block content %}


        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

ecomerce/store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        {% for p in product %}
        <div class="col-lg-4">
            <img class="thumbnail" src="{{ p.imageURL }}" alt="">
            <div class="box-element product">
                <h6><strong>{{p.name}}</strong></h6>
                <hr>
                <button data-product={{p.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to cart</button>
                <a class="btn btn-outline-success" href="#">View</a>
                <h4 style="display: inline-block; float: right;">${{p.price|floatformat:2}}</h4>
            </div>
        </div>
        {% endfor %}
    </div>
    
{% endblock %}