EstradaReneParcial1/EstradaReneParcial1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PNLF/', include('PNLF.urls')),
    path('Jugadores/', include('jugadores.urls')),
    path('Equipos/', include('equipos.urls')),
    path('Estadios/', include('estadios.urls')),
]

EstradaReneParcial1/PNLF/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Inicio, name='Inicio'),
]

EstradaReneParcial1/equipos/urls.py
from django.urls import path
from . import views 

app_name = 'equipos'
urlpatterns = [
    path('Lista-Equipos/', views.ListaEquipos, name='Lista-Equipos'),
    path('Editar-Equipo/', views.EditarEquipo, name='Editar-Equipo'),
    path('Registrar-Equipo/', views.RegistrarEquipo, name='Registrar-Equipo'),
    path('Borrar-Equipo/', views.BorrarEquipo, name='Borrar-Equipo'),
]

EstradaReneParcial1/estadios/urls.py
from django.urls import path 
from . import views

app_name = 'estadios'
urlpatterns = [ 
    path('Lista-Estadios/', views.ListaEstadios, name='Lista-Estadios'),
    path('Registrar-Estadio/', views.RegistrarEstadio, name='Registrar-Estadio'),
    path('Editar-Estadio/', views.EditarEstadio, name='Editar-Estadio'),
    path('Borrar-Estadio/', views.BorrarEstadio, name='Borrar-Estadio'),
]

EstradaReneParcial1/jugadores/urls.py
from django.urls import path
from . import views

app_name = 'jugadores'
urlpatterns = [
    path('Lista-Jugadores/', views.ListaJugadores, name='Lista-Jugadores'),
    path('Registrar-Jugador/', views.RegistrarJugador, name='Registrar-Jugador'),
    path('Editar-Jugador/<int:id>', views.EditarJugador, name='Editar-Jugador'),
    path('Borrar-Jugador/<int:id>', views.BorrarJugador, name='Borrar-Jugador'),
]

EstradaReneParcial1/PNLF/models.py
from django.db import models

# Create your models here.

EstradaReneParcial1/equipos/models.py
from django.db import models

# Create your models here.

class Equipo(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre del equipo: ')
    fechaCreacion = models.DateField(verbose_name='Fundación: ')
    ciudad = models.CharField(max_length=100, verbose_name='Ciudad: ')
    pais = models.CharField(max_length=100, verbose_name='País: ')
    confederacion = models.CharField(max_length=100, verbose_name='Confederación: ')
    # logo = models.ImageField()
    titulos = models.IntegerField(verbose_name='Títulos: ')

    def __str__(self):
        return self.nombre

EstradaReneParcial1/estadios/models.py
from tkinter import CASCADE
from django.db import models
from equipos.models import Equipo
# Create your models here.

class Estadio(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='Nombre del estadio: ')
    capacidad = models.IntegerField(verbose_name='Capacidad: ')
    ciudad = models.CharField(max_length=100, verbose_name='Ciudad: ')
    pais = models.CharField(max_length=100, verbose_name='País: ')
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE, verbose_name='Equipo: ')

    def __str__(self):
        return self.nombre

EstradaReneParcial1/jugadores/models.py
from django.db import models
from equipos.models import Equipo
# Create your models here.

class Jugador(models.Model):
    nombre = models.CharField(max_length=150, verbose_name='Nombre')
    nacionalidad = models.CharField(max_length=100, verbose_name='Nacionalidad')
    posicion = models.CharField(max_length=30, verbose_name='Posición')
    edad = models.IntegerField(verbose_name='Edad')
    estatura = models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Estatura')
    fechaNacimiento = models.DateField(verbose_name='Fecha de nacimiento')
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE, verbose_name='Equipo')

    def __str__(self):
        return self.nombre

EstradaReneParcial1/equipos/forms.py
from django.forms import ModelForm
from .models import Equipo


class RegistrarEquipoForm(ModelForm):
    class Meta:
        model = Equipo
        fields = '__all__'

EstradaReneParcial1/estadios/forms.py
from django.forms import ModelForm
from .models import Estadio


class RegistrarEstadioForm(ModelForm):
    class Meta:
        model = Estadio
        fields = '__all__'

EstradaReneParcial1/jugadores/forms.py
from django.forms import ModelForm
from .models import Jugador


class RegistrarJugadorForm(ModelForm):
    class Meta:
        model = Jugador
        fields = '__all__'

EstradaReneParcial1/PNLF/views.py
from django.shortcuts import render

# Create your views here.

def Inicio(request):
    return render(request, 'base.html')

EstradaReneParcial1/equipos/views.py
from django.shortcuts import render
from .models import Equipo
from .forms import RegistrarEquipoForm

# Create your views here.

def ListaEquipos(request):
    equipo = Equipo.objects.all()
    context = {
        'equipo':equipo
    }
    return render(request, 'equipos/ListaEquipos.html', context)


def RegistrarEquipo(request):
    form = RegistrarEquipoForm()
    if request.method == 'POST':
        form = RegistrarEquipoForm(request.POST)
        if form.is_valid():
            form.save()
    context = {
        'form': form
    }
    return render(request, 'equipos/RegistrarEquipo.html', context)


def EditarEquipo(request):
    return render(request, 'equipos/EditarEquipo.html')


def BorrarEquipo(request):
    return render(request, 'equipos/BorrarEquipo.html')

EstradaReneParcial1/estadios/views.py
from django.shortcuts import render
from .models import Estadio
from .forms import RegistrarEstadioForm
# Create your views here.

def ListaEstadios(request):
    estadio = Estadio.objects.all()
    context = {
        'estadio':estadio
    }
    return render(request, 'estadios/ListaEstadios.html', context)


def RegistrarEstadio(request):
    form = RegistrarEstadioForm()
    if request.method == 'POST':
        form = RegistrarEstadioForm(request.POST)
        if form.is_valid():
            form.save()
    context = {
        'form': form
    }
    return render(request, 'estadios/RegistrarEstadio.html', context)


def EditarEstadio(request):
    return render(request, 'estadios/EditarEstadio.html')


def BorrarEstadio(request):
    return render(request, 'estadios/BorrarEstadio.html')

EstradaReneParcial1/jugadores/views.py
from django.shortcuts import render, redirect
from .models import Jugador
from .forms import RegistrarJugadorForm

# Create your views here.

def ListaJugadores(request):
    jugador = Jugador.objects.all()
    context = {
        'jugador':jugador
    }
    return render(request, 'jugadores/ListaJugadores.html', context)


def RegistrarJugador(request):
    form = RegistrarJugadorForm()
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = RegistrarJugadorForm(request.POST)
        if form.is_valid():
            try:  
                form.save()  
                return redirect('http://127.0.0.1:8000/Jugadores/Lista-Jugadores/')  
            except:  
                pass  
    else:  
        form = RegistrarJugadorForm()  
    return render(request, 'jugadores/RegistrarJugador.html', context)


def EditarJugador(request, id):
    jugador = Jugador.objects.get(id=id)  
    form = RegistrarJugadorForm(request.POST, instance = jugador)  
    if form.is_valid():  
        form.save()  
        return redirect("/Lista-Jugadores")   
    return render(request, 'jugadores/EditarJugador.html', {'form':form})


def BorrarJugador(request, id):
    jugador = Jugador.objects.get(id=id)  
    jugador.delete()  
    return redirect("/Lista-Jugadores")  

EstradaReneParcial1/equipos/templates/equipos/ListaEquipos.html
{% extends 'base.html' %}

{% block content %}

<h1>Lista de equipos</h1>

  
{% for e in equipo %}
    <div>
        <h3>{{ e.nombre }}</h3>
        <p>Año de fundación: {{ e.fechaCreacion }}</p>
        <p>Ciudad: {{ e.ciudad }}</p>
        <p>País: {{ e.pais }}</p>
        <p>Confederación: {{ e.confederacion }}</p>
        <p>Títulos: {{ e.titulos }}</p>
        <div>
            <button>Editar</button>
            <button>Borrar</button>
        </div>
    </div>
{% endfor %}

<a href="{% url 'equipos:Registrar-Equipo' %}">Registrar nuevo equipo</a>

{% endblock %}

EstradaReneParcial1/equipos/templates/equipos/RegistrarEquipo.html
{% extends 'base.html' %}

{% block content %}
<h1>Registrar nuevo equipo</h1>
<form action="." method="POST">
    {% csrf_token %}
    {% for campo in form %}
        <label>{{ campo.label }}</label>
        <input type="{{ campo.field.widget.input_type }}" >
    {% endfor %}t type="submit" value="Registrar">
</form>
    
{% endblock %}

EstradaReneParcial1/estadios/templates/estadios/ListaEstadios.html
{% extends 'base.html' %}

{% block content %}

<h1>Lista de estadios</h1>

  
{% for e in estadio %}
    <div>
        <h3>{{ e.nombre }}</h3>
        <p>Capacidad: {{ e.capacidad }}</p>
        <p>Ciudad: {{ e.ciudad }}</p>
        <p>País: {{ e.pais }}</p>
        <p>Equipo: {{ e.equipo }}</p>
        <div>
            <button>Editar</button>
            <button>Borrar</button>
        </div>
    </div>
{% endfor %}

<a href="{% url 'estadios:Registrar-Estadio' %}">Registrar nuevo estadio</a>

{% endblock %}

EstradaReneParcial1/estadios/templates/estadios/RegistrarEstadio.html
{% extends 'base.html' %}

{% block content %}
<h1>Registrar nuevo estadio</h1>
<form action="." method="POST">
    {% csrf_token %}
    {% csrf_token %}
    {% for campo in form %}
        <label>{{ campo.label }}</label>
        <input type="{{ campo.field.widget.input_type }}" >
    {% endfor %}
</form>
    
{% endblock %}

EstradaReneParcial1/jugadores/templates/jugadores/BorrarJugador.html
{% extends 'base.html' %}

{% block content %}
    <h1>Borrar jugadores</h1>
{% endblock %}

EstradaReneParcial1/jugadores/templates/jugadores/EditarJugador.html
{% extends 'base.html' %}

{% block content %}
    <h1>Editar jugadores</h1>
{% endblock %}

EstradaReneParcial1/jugadores/templates/jugadores/ListaJugadores.html
{% extends 'base.html' %}

{% block content %}

<h1>Lista de jugadores</h1>

  
{% for j in jugador %}
    <div>
        <h3>{{ j.nombre }}</h3>
        <p>Equipo: {{ j.equipo }}</p>
        <p>Posicion: {{ j.posicion }}</p>
        <p>Nacionalidad: {{ j.nacionalidad }}</p>
        <p>Estatura: {{ j.estatura }}</p>
        <p>Edad: {{ j.edad }}</p>
        <div>
            <a href="#">Editar</a>
            <a href="#">Borrar</a>
        </div>
    </div>
{% endfor %}

<a href="{% url 'jugadores:Registrar-Jugador' %}">Registrar nuevo jugador</a>

{% endblock %}

EstradaReneParcial1/jugadores/templates/jugadores/RegistrarJugador.html
{% extends 'base.html' %}

{% block content %}
<h1>Registrar nuevo jugador</h1>
<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Registrar">
</form>
    
{% endblock %}

EstradaReneParcial1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parra National League Football</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'jugadores:Lista-Jugadores' %}">Jugadores</a></li>
                <li><a href="{% url 'equipos:Lista-Equipos' %}">Equipos</a></li>
                <li><a href="{% url 'estadios:Lista-Estadios' %}">Estadios</a></li>
            </ul>
        </nav>
    </header>
    {% block content %}

    {% endblock %}
</body>
</html>