renetflix/pelisyseries/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import *
from . import views
from .forms import UserPasswordResetForm, UserSetPasswordForm, CambiarPasswordForm

app_name = 'pelisyseries'
urlpatterns = [ 
    path('', views.home, name='home' ),
    path('index', views.index, name='index' ),
    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login' ),
    path('logout/', views.logout_request, name='logout' ),
    path('peliculas/', views.peliculas, name='peliculas'),
    path('series/', views.series, name='series'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/accion/', views.accion, name='accion'),
    path('categorias/animacion/', views.animacion, name='animacion'),
    path('categorias/aventura/', views.aventura, name='aventura'),
    path('categorias/terror/', views.terror, name='terror'),
    path('categorias/ciencia_ficcion/', views.ciencia_ficcion, name='ciencia_ficcion'),
    path('categorias/comedia/', views.comedia, name='comedia'),
    path('categorias/drama/', views.drama, name='drama'),
    path('categorias/familiar/', views.familiar, name='familiar'),
    path('categorias/fantasia/', views.fantasia, name='fantasia'),
    path('categorias/misterio/', views.misterio, name='misterio'),
    path('categorias/musicales/', views.musicales, name='musicales'),
    path('recientes/', views.recientes, name='recientes'),
    path('perfil/', views.perfil, name='perfil'),
    path('editar-perfil/', views.EditarPerfil.as_view(), name='editar-perfil'), 
    path('reproducir/<int:id>', views.Reproduccion, name='reproducir'), 
    path('me_gusta/<int:id>', views.Me_gusta, name='me_gusta'),  
    path('favoritos/<int:id>', views.Favoritos, name='favoritos'),  
    path('favoritos/', views.Favoritos_lista, name='favoritos_lista'),  
    path('busqueda/', views.Busqueda, name='busqueda'),  

    path('change_password/', PasswordChangeView.as_view(template_name='registration/change_password.html', form_class=CambiarPasswordForm, success_url = '/'), name='change_password'),

    path('password_reset/', PasswordResetView.as_view(form_class=UserPasswordResetForm, success_url = reverse_lazy('pelisyseries:password_reset_done')), name='password_reset'),  
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),  
    path('password_reset_confirm/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(form_class=UserSetPasswordForm, success_url = reverse_lazy('pelisyseries:password_reset_complete')), name='password_reset_confirm'),  
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),  
]

renetflix/renetflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pelisyseries.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

renetflix/pelisyseries/models.py
from django.db import models
from datetime import datetime, date
from django.contrib.auth.models import User

# Create your models here.
class Contenido(models.Model):
    nombre = models.CharField(max_length=255)
    director = models.CharField(max_length=255)
    estreno = models.DateField(auto_now_add=False, blank=True, null=True)
    descripcion = models.TextField()
    video = models.IntegerField(null=True, blank=True, default=1)
    caratula = models.ImageField(null=True, blank=True, upload_to='myimg')
    tipo = models.CharField(max_length=50, null=True, blank=True)
    genero = models.CharField(max_length=255, null=True, blank=True)
    anio = models.IntegerField(null=True, blank=True)
    meGusta = models.ManyToManyField(User, related_name='Me_Gusta')
    favoritos = models.ManyToManyField(User, related_name='favoritos')

    def __str__(self):
        return f'{self.nombre} : {self.genero}' 

    def me_gusta_total(self):
        return self.meGusta.count()
    

renetflix/pelisyseries/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm
from django.contrib.auth.models import User

class CambiarPasswordForm(PasswordChangeForm):
	old_password = forms.CharField(label='Contraseña actual: ', required=True, widget=forms.PasswordInput())
	new_password1 = forms.CharField(label='Nueva contraseña: ', required=True, widget=forms.PasswordInput())
	new_password2 = forms.CharField(label='Confirmar contraseña: ', required=True, widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ['old_password', 'new_password1', 'new_password2']

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(label='Correo electrónico: ', required=True)

class UserSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(UserSetPasswordForm, self).__init__(*args, **kwargs)

    new_password1 = forms.CharField(label='Nueva contraseña: ', required=True, widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Confirmar contraseña: ', required=True, widget=forms.PasswordInput())

class NewUserForm(UserCreationForm):
	first_name = forms.CharField(label='Nombre(s): ', required=True)
	last_name = forms.CharField(label='Apellido: ', required=True)
	username = forms.CharField(label='Nombre de usuario: ', required=True)
	email = forms.EmailField(label='Correo electrónico: ', required=True)
	password1 = forms.CharField(label='Contraseña: ', required=True, widget=forms.PasswordInput())
	password2 = forms.CharField(label='Confirmar contraseña: ', required=True, widget=forms.PasswordInput())


	class Meta:
		model = User
		fields = ("first_name","last_name", "username", "email", "password1", "password2")
 

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class EditarPerfilForm(UserChangeForm):
	password = None
	first_name = forms.CharField(label='Nombre(s): ')
	last_name = forms.CharField(label='Apellido: ')
	username = forms.CharField(label='Nombre de usuario: ')
	email = forms.EmailField(label='Correo electrónico: ')
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email']

class IniciarSesionForm(AuthenticationForm):
	username = forms.CharField(label='Nombre de usuario: ', required=True)
	password = forms.CharField(label='Contraseña: ', required=True, widget=forms.PasswordInput())
	
	class Meta:
		model=User
		fields = ['username', 'password']

renetflix/pelisyseries/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.models import User 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .forms import *
from .models import *
import datetime
from django.contrib.auth import views as auth_views

# Create your views here.

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			return redirect("pelisyseries:index")
		messages.error(request, "Registro sin éxito. Datos proporcionados no válidos.")
	form = NewUserForm()
	return render (request=request, template_name="pelisyseries/register.html", context={"form":form})


def login_request(request):
	if request.method == "POST":
		form = IniciarSesionForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect("pelisyseries:index")
			else:
				messages.info(request,"Nombre de usuario o contraseña incorrectos.")
		else:
			messages.info(request,"Nombre de usuario o contraseña incorrectos.")
	form = IniciarSesionForm()
	return render(request=request, template_name="pelisyseries/login.html", context={"form":form})

class EditarPerfil(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    redirect_field_name = 'pelisyseries:login'
    form_class=EditarPerfilForm
    template_name='pelisyseries/EditarPerfil.html'
    success_url= reverse_lazy('pelisyseries:perfil')

    def get_object(self):
        return self.request.user

# @login_required(login_url='pelisyseries:home')
def logout_request(request):
    logout(request)
    return redirect('pelisyseries:login')


def home(request):
    if request.user.is_authenticated:
        return redirect('pelisyseries:index')
    else:
        return render(request, 'pelisyseries/home.html')


@login_required(login_url='pelisyseries:login')
def index(request):
    contenido = Contenido.objects.all()
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/index.html', context)

@login_required(login_url='pelisyseries:home')
def peliculas(request):
    contenido = Contenido.objects.filter(tipo='Pelicula')
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/peliculas.html', context)

@login_required(login_url='pelisyseries:home')
def series(request):
    contenido = Contenido.objects.filter(tipo='Serie')
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/series.html', context)

@login_required(login_url='pelisyseries:home')
def categorias(request):
    return render(request, 'pelisyseries/categorias.html')

@login_required(login_url='pelisyseries:home')
def recientes(request):
    d = datetime.date(2022, 9, 1)
    contenido = Contenido.objects.all()
    context = {
        'contenido': contenido,
        'fecha': d
    }
    return render(request, 'pelisyseries/recientes.html', context)

@login_required(login_url='pelisyseries:home')
def accion(request):
    contenido = Contenido.objects.filter(genero='Acción')
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/accion.html', context)

@login_required(login_url='pelisyseries:home')
def animacion(request):
    contenido = Contenido.objects.filter(genero="Animación")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/animacion.html', context)

@login_required(login_url='pelisyseries:home')
def aventura(request):
    contenido = Contenido.objects.filter(genero="Aventura")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/aventura.html', context)

@login_required(login_url='pelisyseries:home')
def terror(request):
    contenido = Contenido.objects.filter(genero="Terror")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/terror.html', context)

@login_required(login_url='pelisyseries:home')
def ciencia_ficcion(request):
    contenido = Contenido.objects.filter(genero="Ciencia Ficción")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/ciencia_ficcion.html', context)

@login_required(login_url='pelisyseries:home')
def comedia(request):
    contenido = Contenido.objects.filter(genero="Comedia")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/comedia.html', context)

@login_required(login_url='pelisyseries:home')
def drama(request):
    contenido = Contenido.objects.filter(genero="Drama")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/drama.html', context)

@login_required(login_url='pelisyseries:home')
def familiar(request):
    contenido = Contenido.objects.filter(genero="Familiar")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/familiar.html', context)

@login_required(login_url='pelisyseries:home')
def fantasia(request):
    contenido = Contenido.objects.filter(genero="Fantasía")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/fantasia.html', context)

@login_required(login_url='pelisyseries:home')
def misterio(request):
    contenido = Contenido.objects.filter(genero="Misterio")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/misterio.html', context)

@login_required(login_url='pelisyseries:home')
def musicales(request):
    contenido = Contenido.objects.filter(genero="Musicales")
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/musicales.html', context)

@login_required(login_url='pelisyseries:home')
def perfil(request):
    return render(request, 'pelisyseries/perfil.html')

@login_required(login_url='pelisyseries:home')
def Reproduccion(request, id):
    contenido = Contenido.objects.get(id=id)
    me_gusta = False
    fav = False

    if contenido.meGusta.filter(id=request.user.id).exists():
        me_gusta = False
    else:
        me_gusta = True

    if contenido.favoritos.filter(id=request.user.id).exists():
        fav = False
    else:
        fav = True

    context = {
        'contenido':contenido,
        'me_gusta':me_gusta,
        'fav':fav,
        }
    return render(request, 'pelisyseries/reproductor.html', context)

@login_required(login_url='pelisyseries:home')
def Me_gusta(request, id):
    contenido = get_object_or_404(Contenido, id=request.POST.get('contenido_id'))
    if contenido.meGusta.filter(id=request.user.id).exists():
        contenido.meGusta.remove(request.user)
    else:
        contenido.meGusta.add(request.user)
    return HttpResponseRedirect(reverse('pelisyseries:reproducir', args=[str(id)]))

@login_required(login_url='pelisyseries:home')
def Favoritos(request, id):
    contenido = get_object_or_404(Contenido, id=request.POST.get('contenido_id'))
    if contenido.favoritos.filter(id=request.user.id).exists():
        contenido.favoritos.remove(request.user)
    else:
        contenido.favoritos.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
    # return HttpResponseRedirect(reverse('pelisyseries:reproducir', args=[str(id)]))

@login_required(login_url='pelisyseries:home')
def Favoritos_lista(request):
    user = request.user
    contenido = user.favoritos.all()
    context = {'contenido': contenido}
    return render(request, 'pelisyseries/favoritas.html', context)

@login_required(login_url='pelisyseries:home')
def Busqueda(request):
    if request.method == 'POST':
        buscar = request.POST['buscar']
        contenido = Contenido.objects.filter(nombre__icontains=buscar)
        return render(request, 'pelisyseries/busqueda.html', {'buscar':buscar, 'contenido':contenido})
    else:
        return render(request, 'pelisyseries/busqueda.html', {'buscar':buscar, 'contenido':contenido})

    

renetflix/pelisyseries/templates/pelisyseries/EditarPerfil.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Renetflix {% endblock title %}

{% block content %}

    <div class="w-25 mt-5 p-4 container text-white-50 border border-3 border-danger rounded rounded-3">
        <h1 class="mt-3 mb-5 text-center">Editar perfil</h1>
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a class="mt-3 mb-3 btn btn-primary" href="{% url 'pelisyseries:perfil' %}">Regresar</a>
                <input class="mt-3 mb-3 btn btn-success" type="submit" value="Guardar">
            </div>
        </form>
    </div>

{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/accion.html
{% extends 'base.html' %}

{% block title %} Renetflix {% endblock title %}

{% block content %}


<div class="mt-5 mb-5 h-100 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/aventura.html
{% extends 'base.html' %}

{% block title %} Renetflix {% endblock title %}

{% block content %}

<div class="mt-5 mb-5 h-100 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/categorias.html
{% extends 'base.html' %}

{% block title %} Categorias {% endblock %}

{% block content %}

<div class="w-75 mx-auto my-5 container text-white">
    <div class="d-flex justify-content-center">
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:accion' %}"><h1 class="fs-3 fw-bold">Acción</h1></a></div>
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:animacion' %}"><h1 class="fs-3 fw-bold">Animación</h1></a></div>
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:aventura' %}"><h1 class="fs-3 fw-bold">Aventura</h1></a></div>
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:terror' %}"><h1 class="fs-3 fw-bold">Terror</h1></a></div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:ciencia_ficcion' %}"><h1 class="fs-3 fw-bold">Ciencia Ficción</h1></a></div>
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:comedia' %}"><h1 class="fs-3 fw-bold">Comedia</h1></a></div>
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:drama' %}"><h1 class="fs-3 fw-bold">Drama</h1></a></div>
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:familiar' %}"><h1 class="fs-3 fw-bold">Familiar</h1></a></div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:fantasia' %}"><h1 class="fs-3 fw-bold">Fantasia</h1></a></div>
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:misterio' %}"><h1 class="fs-3 fw-bold">Misterio</h1></a></div>
        <div class="bg-danger bg-gradient border border-danger rounded m-1 p-5 col-md-3 text-center"><a class="text-dark text-decoration-none" href="{% url 'pelisyseries:musicales' %}"><h1 class="fs-3 fw-bold">Musicales</h1></a></div>
        <div class="m-1 p-5 col-md-3"></div>
    </div>
</div>
<!-- <div class="contenedor-categorias">
    <div class="categorias">
        <a href="{% url 'pelisyseries:accion' %}">Acción</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:animacion' %}">Animación</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:aventura' %}">Aventura</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:terror' %}">Terror</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:ciencia_ficcion' %}">Ciencia Ficción</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:comedia' %}">Comedia</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:drama' %}">Drama</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:familiar' %}">Familiar</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:fantasia' %}">Fantasia</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:misterio' %}">Misterio</a>
    </div>
    <div class="categorias">
        <a href="{% url 'pelisyseries:musicales' %}">Musicales</a>
    </div>
</div> -->

{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/ciencia_ficcion.html
{% extends 'base.html' %}

{% block title %} Renetflix {% endblock title %}

{% block content %}

<div class="mt-5 mb-5 h-100 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/drama.html
{% extends 'base.html' %}

{% block title %} Renetflix {% endblock title %}

{% block content %}

<div class="mt-5 mb-5 h-100 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/favoritas.html
{% extends 'base.html' %}

{% block title %} Renetflix {% endblock title %}

{% block content %}


<div class="mt-5 mb-5 h-100 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Renetflix {% endblock title %}

{% block content %}

    <div class="mx-auto my-5 container w-50">
        <h1 class="fs-1 my-5 fw-bold text-white text-center">¡Bienvenido a Renetflix!</h1>
        <div class="d-grid gap-2 col-6 mx-auto">
            <a href="{% url 'pelisyseries:login' %}" class="btn btn-danger btn-lg">Iniciar sesión</a>
            <a href="{% url 'pelisyseries:register' %}" class="btn btn-danger btn-lg">Crear cuenta</a>
        </div>
    </div>

{% endblock content %}

renetflix/pelisyseries/templates/pelisyseries/index.html
{% extends 'base.html' %}

{% block title %} Renetflix {% endblock title %}

{% block content %}


<div class="mt-5 mb-5 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>

<!-- <div class="contenedor-index">
    {% for p in pelicula %}
        <img src="{{ p.caratula.url }}" alt="" class="imagen-pelicula">
    {% endfor %}

    {% for s in serie %}
        <img src="{{ s.caratula.url }}" alt="" class="imagen-serie">
    {% endfor %}
</div> -->


{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Iniciar sesión {% endblock title %}

{% block content %}
  <div class="w-25 mt-5 p-4 container border border-3 border-danger rounded rounded-3 text-white-50">
    <h1 class="mt-3 mb-5 text-center">Iniciar sesión</h1>
    <form method="POST" autocomplete="off">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="d-grid gap-2">
        <button class="mt-3 mb-3 btn btn-danger" type="submit">Iniciar sesión</button>
      </div>
    </form>
    <p class="mt-2"><a class="text-decoration-none" href="{% url 'pelisyseries:password_reset' %}">¿Olvidaste tu contraseña?</a></p>
    <p><a class="text-decoration-none" href="{% url 'pelisyseries:register' %}">¿No tienes cuenta aún? Regístrate.</a></p>
  </div>
{% endblock content %}

renetflix/pelisyseries/templates/pelisyseries/peliculas.html
{% extends 'base.html' %}

{% block title %} Peliculas {% endblock %}

{% block content %}

<div class="mt-5 mb-5 h-100 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/perfil.html
{% extends 'base.html' %}

{% block title %} Perfil {% endblock title %}

{% block content %}

<div class="w-25 mt-5 p-4 container border border-3 border-danger rounded rounded-3 text-white-50">
    <h1 class="mt-3 mb-5 text-center">Información de cuenta</h1>
    <hr>
    <label for="" class="mt-2 text-white-50">Nombre:</label>
    <p class="mb-2 fs-3 text-white">{{user.first_name}} {{user.last_name}}</p>
    <label for="" class="mt-2 text-white-50">Nombre de usuairo:</label>
    <p class="mb-2 fs-3 text-white">{{user.username}}</p>
    <label for="" class="mt-2 text-white-50">Correo electrónico:</label>
    <p class="mb-2 fs-3 text-white">{{user.email}}</p>
    <label for="" class="mt-2 text-white-50">Fecha de creación:</label>
    <p class="mb-2 fs-3 text-white">{{user.date_joined}}</p>
    <div class="d-grid gap-2">
        <a class="mt-3 mb-1 btn btn-danger" href="{% url 'pelisyseries:editar-perfil' %}">Editar perfil</a>
        <a class="mb-3 btn btn-danger" href="{% url 'pelisyseries:change_password' %}">Cambiar contraseña</a>
    </div>
</div>

{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/series.html
{% extends 'base.html' %}

{% block title %} Series {% endblock %}

{% block content %}

<div class="mt-5 mb-5 h-100 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

renetflix/pelisyseries/templates/pelisyseries/terror.html
{% extends 'base.html' %}

{% block title %} Renetflix {% endblock title %}

{% block content %}

<div class="mt-5 mb-5 h-100 container">
    <div class="row">
        {% for c in contenido %}
            <div class="mt-1 mb-1 col-md-3">
                <a href="{% url 'pelisyseries:reproducir' c.id %}"><img class="rounded" width="320px" height="200px" src="{{ c.caratula.url }}"></a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}